DROP DATABASE IF EXISTS COLOSSEUM;
CREATE DATABASE COLOSSEUM;
USE COLOSSEUM;
SHOW TABLES;

/*
For historical reasons any integer/decimal number that would usually be represented as so 
will be represented in Roman numerals for historical purposes.
*/

CREATE TABLE GLADIATOR(
	GLADIATOR_ID VARCHAR(4) PRIMARY KEY, 
    FIRST_NAME VARCHAR(25) NOT NULL,
    LAST_NAME VARCHAR(25) NOT NULL,
    SUFFIX VARCHAR(5),
    AGE VARCHAR(4),
    BIOGRAPHY VARCHAR(200)
    );
    
CREATE TABLE ARMORY(
	WEAPON_ID VARCHAR(4) PRIMARY KEY,
	WEAPON_TYPE VARCHAR(50),
    LONG_RANGE CHAR(1) NOT NULL, #Can be T or F
    MATERIAL VARCHAR(20) NOT NULL
    );


CREATE TABLE ANIMAL(
	SPECIES VARCHAR(50) PRIMARY KEY,
    GOLD_COIN VARCHAR(4),
    SILVER_COIN VARCHAR(4),
    BRONZE_COIN VARCHAR(4)
    );

/*
A Lanista is comparable to a manager/boss of gladiator(s).
CREATE TABLE LANISTA();*/

CREATE TABLE EXHIBITION (
GLADIATOR VARCHAR(4), #Add weapon relation, it is many to many so a bridge has to be created with the weapons table
SPECIES VARCHAR(50),
#WEAPON_TYPE VARCHAR(50), Limit is 2
#DEGREES
#CLOUDS
#WIND
PRIMARY KEY (GLADIATOR, SPECIES),
FOREIGN KEY (GLADIATOR) REFERENCES GLADIATOR(GLADIATOR_ID),
FOREIGN KEY (SPECIES) REFERENCES ANIMAL_TYPE(SPECIES)
);
    
SHOW TABLES;