DROP DATABASE IF EXISTS COLOSSEUM;
CREATE DATABASE COLOSSEUM;
USE COLOSSEUM;

SHOW TABLES;

CREATE TABLE GLADIATOR (
	GLADIATOR_NAME VARCHAR(20) PRIMARY KEY,
    AGE DECIMAL,
    BIOGRAPHY VARCHAR(20)
    );
    
CREATE TABLE WEAPON (
	NAME VARCHAR(20) PRIMARY KEY,
    WEAPON_TYPE VARCHAR(20),
    MATERIAL VARCHAR(20)
    );


CREATE TABLE ANIMAL (
	ANIMAL_NAME VARCHAR(20) PRIMARY KEY,
    ANIMAL_TYPE VARCHAR(20),
    REWARD VARCHAR(20)
    );

CREATE TABLE EXHIBITION (
GLADIATOR_NAME VARCHAR(20),
ANIMAL_NAME VARCHAR(20),
PRIMARY KEY (GLADIATOR_NAME, ANIMAL_NAME),
FOREIGN KEY (GLADIATOR_NAME) REFERENCES GLADIATOR(GLADIATOR_NAME),
FOREIGN KEY (ANIMAL_NAME) REFERENCES ANIMAL(ANIMAL_NAME)
);
    
SHOW TABLES;