DROP DATABASE IF EXISTS COLOSSEUM;
CREATE DATABASE COLOSSEUM;
USE COLOSSEUM;

SHOW TABLES;

CREATE TABLE GLADIATOR (
	GLADIATOR_ID VARCHAR(4) PRIMARY KEY, #Gladiator will be in Roman numerals. E.G. I, II, VI, etc
    FIRST_NAME VARCHAR(20) NOT NULL,
    LAST_NAME VARCHAR(25) NOT NULL,
    SUFFIX VARCHAR(5),
    AGE VARCHAR(4), #Gladiator will have an age in Roman numerals
    BIOGRAPHY VARCHAR(200)
    );
    
CREATE TABLE WEAPON (
	WEAPON_TYPE VARCHAR(50) PRIMARY KEY, #Assume all weapons have a unique name
    LONG_RANGE BOOLEAN NOT NULL, #If true the weapons is long range
    MATERIAL VARCHAR(20) NOT NULL
    );


CREATE TABLE ANIMAL_TYPE(
	SPECIES VARCHAR(50) PRIMARY KEY,
    GOLD_COIN INT NOT NULL,
    SILVER_COIN INT NOT NULL,
    BRONZE_COINT INT NOT NULL
    );

CREATE TABLE EXHIBITION (
GLADIATOR_ID VARCHAR(4), #Add weapon relation, it is many to many so a bridge has to be created with the weapons table
SPECIES VARCHAR(50),
WEAPON_TYPE VARCHAR(50), #Limit is 2
PRIMARY KEY (GLADIATOR_NAME, ANIMAL_NAME, WEAPON_TYPE),
FOREIGN KEY (GLADIATOR_ID) REFERENCES GLADIATOR(GLADIATOR_ID),
FOREIGN KEY (SPECIES) REFERENCES ANIMAL_TYPE(SPECIES),
FOREIGN KEY (WEAPON_TYPE) REFERENCES WEAPON(WEAPON_TYPE)
);
    
SHOW TABLES;